/**
 * Test case CRUD and persistence.
 *
 * Test cases are generated from saved workflows by an LLM (testGen.js) and
 * stored in `.qase/test-cases.json`. Each test case has a sequence of steps
 * (the actions to replay) and assertions (what to check after each step).
 *
 * In Phase 3, the replay engine will execute these against a live browser.
 */

import { randomUUID } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { removeTestCaseFromAllFindings } from './findings.js';
import { atomicWrite } from './atomicWrite.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEST_CASES_FILE = join(__dirname, '..', '.qase', 'test-cases.json');

let testCases = [];
let saveTimer = null;

function loadTestCases() {
	try {
		if (existsSync(TEST_CASES_FILE)) {
			testCases = JSON.parse(readFileSync(TEST_CASES_FILE, 'utf-8'));
			// Backfill Phase 8 + Phase 14 fields on load.
			for (const tc of testCases) {
			tc.tags = tc.tags ?? [];
			tc.suiteId = tc.suiteId ?? null;
			tc.findingIds = tc.findingIds ?? [];
			tc.viewport = tc.viewport ?? null;
			tc.viewports = tc.viewports ?? [];
			}
		}
	} catch {
		testCases = [];
	}
}

function persistSoon() {
	if (saveTimer) {
		return;
	}
	saveTimer = setTimeout(() => {
		saveTimer = null;
		flush();
	}, 250);
}

function flush() {
	try {
		atomicWrite(TEST_CASES_FILE, JSON.stringify(testCases, null, '\t'));
	} catch (error) {
		console.log('Failed to persist test cases:', error.message);
	}
}

/** Immediately persist the in-memory test cases array to disk. */
export function saveTestCasesRaw() {
	flush();
}

/**
 * Backfill: assign defaultId to every test case missing a projectId.
 * Returns the number updated.
 */
export function backfillProjectId(defaultId) {
	let count = 0;
	for (const tc of testCases) {
		if (!tc.projectId) {
			tc.projectId = defaultId;
			count++;
		}
	}
	if (count > 0) flush();
	return count;
}

/**
 * Reassign: move all test cases from fromProjectId to toProjectId.
 * Returns the number moved.
 */
export function reassignProjectId(fromProjectId, toProjectId) {
	let count = 0;
	for (const tc of testCases) {
		if (tc.projectId === fromProjectId) {
			tc.projectId = toProjectId;
			count++;
		}
	}
	if (count > 0) flush();
	return count;
}

loadTestCases();

/* ── Schema helpers ─────────────────────────────────────────────── */

export function validateTestCase(tc) {
	const errors = [];
	if (!tc.name || typeof tc.name !== 'string') {
		errors.push('name is required');
	}
	if (!Array.isArray(tc.steps)) {
		errors.push('steps must be an array');
	}
	if (!Array.isArray(tc.assertions)) {
		errors.push('assertions must be an array');
	}
	return errors;
}

/* ── CRUD ───────────────────────────────────────────────────────── */

export function createTestCase(data) {
	const tc = {
		id: randomUUID(),
		projectId: data.projectId ?? undefined,
		workflowId: data.workflowId ?? null,
		suiteId: data.suiteId ?? null,
		name: data.name ?? 'Untitled test case',
		targetUrl: data.targetUrl ?? '',
		preconditions: Array.isArray(data.preconditions) ? data.preconditions : [],
		steps: Array.isArray(data.steps) ? data.steps : [],
		assertions: Array.isArray(data.assertions) ? data.assertions : [],
		severity: data.severity ?? 'medium',
		tags: Array.isArray(data.tags) ? data.tags : [],
		viewport: data.viewport ?? null,
		viewports: Array.isArray(data.viewports) ? data.viewports : [],
		createdAt: Date.now(),
		updatedAt: Date.now(),
		lastRun: undefined
	};
	testCases.push(tc);
	persistSoon();
	return tc;
}

/**
 * Stores one or more test cases generated by the LLM. Each record is
 * normalised and given an id/timestamps before being added.
 */
export function createTestCases(records, { projectId, workflowId, targetUrl } = {}) {
	const created = [];
	for (const record of records) {
		created.push(createTestCase({
			...record,
			projectId: record.projectId ?? projectId,
			workflowId: record.workflowId ?? workflowId,
			targetUrl: record.targetUrl ?? targetUrl
		}));
	}
	return created;
}

export function listTestCases({ projectId, targetUrl, workflowId, suiteId, tag } = {}) {
	return testCases
		.filter(tc => {
			if (projectId && tc.projectId !== projectId) return false;
			if (targetUrl && tc.targetUrl !== targetUrl) return false;
			if (workflowId && tc.workflowId !== workflowId) return false;
			if (suiteId !== undefined && tc.suiteId !== suiteId) return false;
			if (tag && !(tc.tags ?? []).includes(tag)) return false;
			return true;
		})
		.sort((a, b) => b.updatedAt - a.updatedAt);
}

export function getTestCase(id) {
	return testCases.find(tc => tc.id === id);
}

export function updateTestCase(id, patch) {
	const tc = testCases.find(t => t.id === id);
	if (!tc) return undefined;

	if (typeof patch.name === 'string') tc.name = patch.name;
	if (typeof patch.severity === 'string') tc.severity = patch.severity;
	if (typeof patch.targetUrl === 'string') tc.targetUrl = patch.targetUrl;
	if (Array.isArray(patch.preconditions)) tc.preconditions = patch.preconditions;
	if (Array.isArray(patch.steps)) tc.steps = patch.steps;
	if (Array.isArray(patch.assertions)) tc.assertions = patch.assertions;
	if (Array.isArray(patch.tags)) tc.tags = patch.tags;
	if (Array.isArray(patch.findingIds)) tc.findingIds = patch.findingIds;
	if (patch.suiteId !== undefined) tc.suiteId = patch.suiteId;
	if (patch.viewport !== undefined) tc.viewport = patch.viewport;
	if (Array.isArray(patch.viewports)) tc.viewports = patch.viewports;

	tc.updatedAt = Date.now();
	persistSoon();
	return tc;
}

/**
 * Clones a test case. The clone gets a new id, a " (copy)" suffix on the name,
 * and copies of all steps, assertions, preconditions, and tags. It retains
 * the same projectId and targetUrl but gets a new suiteId only if the
 * original has one.
 */
export function cloneTestCase(id) {
	const original = testCases.find(tc => tc.id === id);
	if (!original) return undefined;

	const clone = createTestCase({
		projectId: original.projectId,
		workflowId: null,
		suiteId: original.suiteId ?? null,
		name: `${original.name} (copy)`,
		targetUrl: original.targetUrl,
		preconditions: [...(original.preconditions ?? [])],
		steps: (original.steps ?? []).map(s => ({ ...s })),
		assertions: (original.assertions ?? []).map(a => ({ ...a })),
		severity: original.severity,
		tags: [...(original.tags ?? [])],
		viewport: original.viewport ?? null,
		viewports: [...(original.viewports ?? [])]
	});

	return clone;
}

/**
 * Returns all distinct tags across all test cases (optionally scoped by projectId).
 */
export function listTags({ projectId } = {}) {
	const tags = new Set();
	for (const tc of testCases) {
		if (projectId && tc.projectId !== projectId) continue;
		for (const tag of tc.tags ?? []) {
			tags.add(tag);
		}
	}
	return [...tags].sort();
}

export function deleteTestCase(id) {
	const index = testCases.findIndex(tc => tc.id === id);
	if (index === -1) return false;
	testCases.splice(index, 1);
	persistSoon();
	// Phase 11: remove this test case from all findings that reference it.
	try {
		removeTestCaseFromAllFindings(id);
	} catch { /* non-fatal */ }
	return true;
}

export function deleteTestCasesByWorkflow(workflowId) {
	const before = testCases.length;
	testCases = testCases.filter(tc => tc.workflowId !== workflowId);
	if (testCases.length !== before) persistSoon();
	return before - testCases.length;
}
